Repository rust-lang/miri, pull requests merged in 2022-07, with the labels that each got.

#1935 Optimizing Stacked Borrows (part 1?): Cache locations of Tags in a Borrow Stack
  Cargo.toml
  src/lib.rs
  src/stacked_borrows.rs
  src/stacked_borrows/diagnostics.rs
  src/stacked_borrows/stack.rs
Labels: S-waiting-on-author

#2323 handle Box with allocators
  src/stacked_borrows.rs
  tests/pass/box-custom-alloc.rs
Labels: S-blocked-on-rust

#2315 Optimizing Stacked Borrows (part 2): Shrink Item
  src/lib.rs
  src/machine.rs
  src/stacked_borrows.rs
  src/stacked_borrows/diagnostics.rs
  src/stacked_borrows/item.rs
  src/stacked_borrows/stack.rs
  src/thread.rs
  tests/compiletest.rs
  tests/fail/stacked_borrows/aliasing_mut1.stderr
  tests/fail/stacked_borrows/aliasing_mut2.stderr
  tests/fail/stacked_borrows/aliasing_mut4.stderr
  tests/fail/stacked_borrows/deallocate_against_barrier1.rs
  tests/fail/stacked_borrows/deallocate_against_barrier1.stderr
  tests/fail/stacked_borrows/deallocate_against_barrier2.rs
  tests/fail/stacked_borrows/deallocate_against_barrier2.stderr
  tests/fail/stacked_borrows/illegal_write6.stderr
  tests/fail/stacked_borrows/invalidate_against_barrier1.stderr
  tests/fail/stacked_borrows/invalidate_against_barrier2.stderr
  tests/fail/stacked_borrows/newtype_retagging.rs
  tests/fail/stacked_borrows/newtype_retagging.stderr
Labels: S-waiting-on-author

#2349 Improve isatty support
  src/shims/unix/foreign_items.rs
  src/shims/unix/fs.rs
  tests/pass/libc.rs
Labels: S-waiting-on-author

#2383 Print one . character per test instead of one line
  tests/compiletest.rs
  ui_test/src/lib.rs
  ui_test/src/tests.rs
Labels: S-waiting-on-author

#2035 portable-simd: test bitmasks smaller than a byte
  rust-version
  tests/fail/intrinsics/simd-float-to-int.stderr
  tests/pass/portable-simd.rs
Labels: S-blocked-on-rust

#2434 ui_test: build dependencies in locked mode unless bless is enabled
  ui_test/src/dependencies.rs
Labels: S-waiting-on-review

#2436 fix build.rs invoking RUSTC to do check builds
  README.md
  cargo-miri/bin.rs
  miri
  src/bin/miri.rs
  test-cargo-miri/Cargo.lock
  test-cargo-miri/Cargo.toml
  test-cargo-miri/build.rs
  tests/compiletest.rs
Labels: S-waiting-on-review

#2438 adjust for more backtrace pruning
  rust-version
  tests/fail/intrinsics/copy_overflow.rs
  tests/fail/intrinsics/copy_overflow.stderr
  tests/fail/intrinsics/out_of_bounds_ptr_1.rs
  tests/fail/intrinsics/out_of_bounds_ptr_1.stderr
  tests/fail/intrinsics/out_of_bounds_ptr_2.rs
  tests/fail/intrinsics/out_of_bounds_ptr_2.stderr
  tests/fail/intrinsics/out_of_bounds_ptr_3.rs
  tests/fail/intrinsics/out_of_bounds_ptr_3.stderr
  tests/fail/intrinsics/overflowing-unchecked-rsh.rs
  tests/fail/intrinsics/overflowing-unchecked-rsh.stderr
  tests/fail/intrinsics/ptr_offset_0_plus_0.rs
  tests/fail/intrinsics/ptr_offset_0_plus_0.stderr
  tests/fail/intrinsics/ptr_offset_from_oob.rs
  tests/fail/intrinsics/ptr_offset_from_oob.stderr
  tests/fail/intrinsics/ptr_offset_from_unsigned_neg.rs
  tests/fail/intrinsics/ptr_offset_from_unsigned_neg.stderr
  tests/fail/intrinsics/ptr_offset_int_plus_int.rs
  tests/fail/intrinsics/ptr_offset_int_plus_int.stderr
  tests/fail/intrinsics/ptr_offset_int_plus_ptr.rs
  tests/fail/intrinsics/ptr_offset_int_plus_ptr.stderr
  tests/fail/intrinsics/ptr_offset_overflow.rs
  tests/fail/intrinsics/ptr_offset_overflow.stderr
  tests/fail/intrinsics/ptr_offset_ptr_plus_0.rs
  tests/fail/intrinsics/ptr_offset_ptr_plus_0.stderr
  tests/fail/intrinsics/unchecked_add1.rs
  tests/fail/intrinsics/unchecked_add1.stderr
  tests/fail/intrinsics/unchecked_add2.rs
  tests/fail/intrinsics/unchecked_add2.stderr
  tests/fail/intrinsics/unchecked_mul1.rs
  tests/fail/intrinsics/unchecked_mul1.stderr
  tests/fail/intrinsics/unchecked_mul2.rs
  tests/fail/intrinsics/unchecked_mul2.stderr
  tests/fail/intrinsics/unchecked_sub1.rs
  tests/fail/intrinsics/unchecked_sub1.stderr
  tests/fail/intrinsics/unchecked_sub2.rs
  tests/fail/intrinsics/unchecked_sub2.stderr
  tests/fail/invalid_enum_tag.rs
  tests/fail/invalid_enum_tag.stderr
  tests/fail/provenance/ptr_invalid_offset.rs
  tests/fail/provenance/ptr_invalid_offset.stderr
  tests/fail/should-pass/cpp20_rwc_syncs.rs
  tests/fail/should-pass/cpp20_rwc_syncs.stderr
  tests/fail/unreachable.rs
  tests/fail/unreachable.stderr
  tests/fail/weak_memory/racing_mixed_size.rs
Labels: S-blocked-on-rust

#2426 Use real exec on cfg(unix) targets
  cargo-miri/bin.rs
Labels: S-waiting-on-review
