Repository rust-lang/miri, pull requests merged in 2022-08, with the labels that each got.

#2346 Add `mkstemp` shim for unix
  src/shims/unix/foreign_items.rs
  src/shims/unix/fs.rs
  tests/fail/fs/mkstemp_immutable_arg.rs
  tests/fail/fs/mkstemp_immutable_arg.stderr
  tests/pass/libc.rs
Labels: S-waiting-on-review

#2471 stop excluding TERM env var on Unix
  README.md
  rust-version
  src/shims/env.rs
Labels: S-blocked-on-rust

#2464 Atomics must be mutable
  rust-version
  src/concurrency/data_race.rs
  src/shims/intrinsics/atomic.rs
  src/shims/unix/linux/sync.rs
  tests/fail/concurrency/read_only_atomic_cmpxchg.rs
  tests/fail/concurrency/read_only_atomic_cmpxchg.stderr
  tests/fail/concurrency/read_only_atomic_load.rs
  tests/fail/concurrency/read_only_atomic_load.stderr
  tests/pass/concurrency/linux-futex.rs
Labels: S-blocked-on-rust

#2441 pass clippy::integer_arithmetic in our shims
  src/lib.rs
  src/shims/backtrace.rs
  src/shims/foreign_items.rs
  src/shims/intrinsics/simd.rs
  src/shims/mod.rs
  src/shims/time.rs
  src/shims/tls.rs
  src/shims/unix/fs.rs
  src/shims/unix/linux/sync.rs
  src/shims/windows/handle.rs
Labels: S-waiting-on-review

#2481 document general shim pattern
  src/shims/foreign_items.rs
  src/shims/unix/foreign_items.rs
  src/shims/unix/linux/foreign_items.rs
  src/shims/unix/macos/foreign_items.rs
  src/shims/windows/foreign_items.rs
Labels: S-waiting-on-review

#2448 Run `pass` tests without building dependencies first
  tests/compiletest.rs
  tests/pass-dep/calloc.rs
  tests/pass-dep/concurrency/libc_pthread_cond.rs
  tests/pass-dep/concurrency/linux-futex.rs
  tests/pass-dep/concurrency/tls_pthread_drop_order.rs
  tests/pass-dep/foreign-fn-linkname.rs
  tests/pass-dep/malloc.rs
  tests/pass-dep/num_cpus.rs
  tests/pass-dep/page_size.rs
  tests/pass-dep/random.rs
  tests/pass-dep/regions-mock-trans.rs
  tests/pass-dep/shims/fs.rs
  tests/pass-dep/shims/fs.stderr
  tests/pass-dep/shims/fs.stdout
  tests/pass-dep/shims/fs_with_isolation.rs
  tests/pass-dep/shims/fs_with_isolation.stderr
  tests/pass-dep/shims/libc-misc.rs
  tests/pass-dep/shims/linux-getrandom-without-isolation.rs
  tests/pass-dep/shims/linux-getrandom.rs
  tests/pass-dep/shims/posix_memalign.rs
  tests/pass-dep/shims/pthreads.rs
Labels: S-waiting-on-review

#2449 Use ui_test from crates.io instead of having it in-tree
  Cargo.lock
  Cargo.toml
  miri
  ui_test/Cargo.lock
  ui_test/Cargo.toml
  ui_test/README.md
  ui_test/src/dependencies.rs
  ui_test/src/lib.rs
  ui_test/src/parser.rs
  ui_test/src/parser/tests.rs
  ui_test/src/rustc_stderr.rs
  ui_test/src/tests.rs
Labels: S-waiting-on-author

#2363 Adding support for external C functions that have integer (or empty) args and/or returns
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  build.rs
  miri
  src/bin/miri.rs
  src/eval.rs
  src/machine.rs
  src/shims/ffi_support.rs
  src/shims/foreign_items.rs
  src/shims/mod.rs
  tests/compiletest.rs
  tests/extern-so/fail/function_not_in_so.rs
  tests/extern-so/fail/function_not_in_so.stderr
  tests/extern-so/libcode.version
  tests/extern-so/pass/call_extern_c_fcts.rs
  tests/extern-so/pass/call_extern_c_fcts.stdout
  tests/extern-so/test.c
Labels: S-waiting-on-author

#2455 adjust for earlier init checking in the core engine
  rust-version
  src/concurrency/data_race.rs
  src/concurrency/weak_memory.rs
  src/helpers.rs
  src/machine.rs
  src/operator.rs
  src/shims/ffi_support.rs
  src/shims/intrinsics/mod.rs
  src/shims/intrinsics/simd.rs
  src/shims/os_str.rs
  src/shims/panic.rs
  src/shims/unix/foreign_items.rs
  src/shims/unix/freebsd/foreign_items.rs
  src/shims/unix/linux/foreign_items.rs
  src/shims/unix/linux/sync.rs
  src/shims/unix/macos/foreign_items.rs
  src/shims/unix/sync.rs
  src/shims/windows/dlsym.rs
  src/shims/windows/foreign_items.rs
  src/shims/windows/handle.rs
  src/shims/windows/sync.rs
  src/shims/windows/thread.rs
  tests/fail/invalid_int.rs
  tests/fail/invalid_int.stderr
  tests/fail/transmute-pair-uninit.stderr
  tests/fail/uninit_byte_read.stderr
  tests/fail/validity/invalid_bool_uninit.rs
  tests/fail/validity/invalid_bool_uninit.stderr
  tests/fail/validity/invalid_char_uninit.rs
  tests/fail/validity/invalid_char_uninit.stderr
  tests/fail/validity/invalid_fnptr_uninit.rs
  tests/fail/validity/invalid_fnptr_uninit.stderr
  tests/fail/validity/uninit_float.rs
  tests/fail/validity/uninit_float.stderr
  tests/fail/validity/uninit_integer.rs
  tests/fail/validity/uninit_integer.stderr
  tests/fail/validity/uninit_raw_ptr.rs
  tests/fail/validity/uninit_raw_ptr.stderr
  tests/pass/issues/issue-miri-2068-2.rs
Labels: S-blocked-on-rust
