Repository rust-lang/miri, pull requests merged in 2024-08, with the labels that each got.

#3795 throw_unsup_format for alignment greater than 2^29
  src/shims/foreign_items.rs
  tests/fail/alloc/unsupported_big_alignment.rs
  tests/fail/alloc/unsupported_big_alignment.stderr
  tests/fail/alloc/unsupported_non_power_two_alignment.rs
  tests/fail/alloc/unsupported_non_power_two_alignment.stderr
Labels: S-waiting-on-review

#3712 Implement epoll shim
  src/helpers.rs
  src/machine.rs
  src/shims/mod.rs
  src/shims/unix/fd.rs
  src/shims/unix/fs.rs
  src/shims/unix/linux/epoll.rs
  src/shims/unix/linux/eventfd.rs
  src/shims/unix/mod.rs
  src/shims/unix/socket.rs
  tests/fail-dep/tokio/sleep.rs
  tests/fail-dep/tokio/sleep.stderr
  tests/pass-dep/libc/libc-epoll.rs
Labels: S-waiting-on-review

#3754 Make unused states of Reserved unrepresentable
  src/borrow_tracker/tree_borrows/mod.rs
  src/borrow_tracker/tree_borrows/perms.rs
  src/borrow_tracker/tree_borrows/tree/tests.rs
  tests/fail/tree_borrows/reserved/cell-protected-write.stderr
  tests/fail/tree_borrows/reserved/int-protected-write.stderr
  tests/pass/tree_borrows/cell-alternate-writes.stderr
  tests/pass/tree_borrows/end-of-protector.stderr
  tests/pass/tree_borrows/formatting.stderr
  tests/pass/tree_borrows/reborrow-is-read.stderr
  tests/pass/tree_borrows/reserved.stderr
  tests/pass/tree_borrows/unique.default.stderr
  tests/pass/tree_borrows/unique.uniq.stderr
  tests/pass/tree_borrows/vec_unique.default.stderr
Labels: S-waiting-on-review

#3814 Add epoll EPOLLHUP flag support
  src/shims/unix/linux/epoll.rs
  src/shims/unix/socket.rs
  tests/pass-dep/libc/libc-epoll.rs
Labels: S-waiting-on-review

#3813 Testcase fix for epoll
  tests/pass-dep/libc/libc-epoll.rs
Labels: S-waiting-on-review

#3818 epoll: iterate through output buffer then fetch an event from ready list
  src/shims/unix/linux/epoll.rs
  tests/pass-dep/libc/libc-epoll.rs
Labels: S-waiting-on-author

#3820 Add epollerr support
  src/shims/unix/linux/epoll.rs
  src/shims/unix/unnamed_socket.rs
  tests/pass-dep/libc/libc-epoll.rs
Labels: S-waiting-on-author

#3748 readdir_r shim: assume FreeBSD v12+
  src/shims/unix/fs.rs
  test_dependencies/Cargo.lock
Labels: S-blocked

#3829 epoll: handle edge case for epoll_ctl
  src/shims/unix/linux/epoll.rs
  tests/fail-dep/libc/libc_epoll_unsupported_fd.rs
  tests/fail-dep/libc/libc_epoll_unsupported_fd.stderr
  tests/pass-dep/libc/libc-epoll.rs
Labels: S-waiting-on-review

#3804 Support blocking for epoll
  src/concurrency/thread.rs
  src/shims/unix/fd.rs
  src/shims/unix/linux/epoll.rs
  src/shims/unix/linux/foreign_items.rs
  tests/fail-dep/tokio/sleep.stderr
  tests/pass-dep/libc/libc-epoll-blocking.rs
  tests/pass-dep/libc/libc-epoll-no-blocking.rs
  tests/pass-dep/tokio/sleep.rs
Labels: S-waiting-on-review
