Repository rust-lang/miri, pull requests merged in 2024-10, with the labels that each got.

#3895 Implement LLVM x86 gfni intrinsics
  src/shims/x86/gfni.rs
  src/shims/x86/mod.rs
  tests/pass/shims/x86/intrinsics-x86-gfni.rs
Labels: S-waiting-on-review

#3946 Fix over synchronization of epoll
  src/shims/unix/linux/epoll.rs
  tests/fail-dep/libc/libc-epoll-data-race.rs
  tests/fail-dep/libc/libc-epoll-data-race.stderr
Labels: S-waiting-on-review

#3937 syscall eventfd2
  src/shims/unix/linux/foreign_items.rs
  tests/pass-dep/libc/libc-eventfd.rs
Labels: S-waiting-on-review

#3960 Pipe minor changes: diagnostics, flag support and comments
  ci/ci.sh
  src/shims/unix/foreign_items.rs
  src/shims/unix/unnamed_socket.rs
  tests/fail-dep/libc/socketpair_read_blocking.stderr
  tests/fail-dep/libc/socketpair_write_blocking.stderr
  tests/pass-dep/libc/libc-epoll-blocking.rs
  tests/pass-dep/libc/libc-pipe.rs
Labels: S-waiting-on-review

#3957 Fixed get/set thread name implementations for macOS and FreeBSD
  src/shims/unix/freebsd/foreign_items.rs
  src/shims/unix/linux/foreign_items.rs
  src/shims/unix/macos/foreign_items.rs
  src/shims/unix/solarish/foreign_items.rs
  src/shims/unix/thread.rs
  tests/pass-dep/libc/pthread-threadname.rs
  tests/pass/concurrency/threadname.rs
Labels: S-waiting-on-review

#3966 Do not store synchronization primitive IDs in adressable memory
  src/concurrency/init_once.rs
  src/concurrency/sync.rs
  src/helpers.rs
  src/machine.rs
  src/shims/unix/macos/sync.rs
  src/shims/unix/sync.rs
  src/shims/windows/sync.rs
  tests/fail-dep/concurrency/libc_pthread_cond_move.init.stderr
  tests/fail-dep/concurrency/libc_pthread_cond_move.rs
  tests/fail-dep/concurrency/libc_pthread_cond_move.static_initializer.stderr
  tests/fail-dep/concurrency/libc_pthread_mutex_move.init.stderr
  tests/fail-dep/concurrency/libc_pthread_mutex_move.rs
  tests/fail-dep/concurrency/libc_pthread_mutex_move.static_initializer.stderr
  tests/fail-dep/concurrency/libx_pthread_rwlock_moved.rs
  tests/fail-dep/concurrency/libx_pthread_rwlock_moved.stderr
Labels: S-blocked

#3941 Replace set_last_error with set_last_error_and_return
  src/shims/io_error.rs
  src/shims/unix/fd.rs
  src/shims/unix/fs.rs
  src/shims/unix/linux/epoll.rs
  src/shims/unix/mem.rs
Labels: S-waiting-on-author

#3899 Android: Added support for prctl handling thread names
  ci/ci.sh
  src/shims/unix/android/foreign_items.rs
  src/shims/unix/android/mod.rs
  src/shims/unix/android/thread.rs
  src/shims/unix/freebsd/foreign_items.rs
  src/shims/unix/linux/foreign_items.rs
  src/shims/unix/macos/foreign_items.rs
  src/shims/unix/solarish/foreign_items.rs
  src/shims/unix/thread.rs
  test_dependencies/Cargo.lock
  tests/fail-dep/libc/prctl-get-name-buffer-too-small.rs
  tests/fail-dep/libc/prctl-get-name-buffer-too-small.stderr
  tests/pass-dep/libc/prctl-threadname.rs
  tests/pass-dep/libc/pthread-threadname.rs
Labels: S-waiting-on-author

#3984 Clear `eval_libc` errors from unix shims
  src/shims/foreign_items.rs
  src/shims/time.rs
  src/shims/unix/foreign_items.rs
  src/shims/unix/fs.rs
  src/shims/unix/linux/mem.rs
  src/shims/unix/linux/sync.rs
  src/shims/unix/mem.rs
Labels: S-waiting-on-review

#3987 Implement LLVM x86 vpclmulqdq intrinsics
  src/shims/x86/mod.rs
  tests/pass/shims/x86/intrinsics-x86-vpclmulqdq.rs
Labels: S-waiting-on-review

#3954 Add option for generating coverage reports
  .github/workflows/ci.yml
  miri-script/Cargo.lock
  miri-script/Cargo.toml
  miri-script/src/commands.rs
  miri-script/src/coverage.rs
  miri-script/src/main.rs
  miri-script/src/util.rs
Labels: S-waiting-on-review

#4000 Change futex_wait errno from Scalar to IoError
  src/concurrency/sync.rs
  src/provenance_gc.rs
  src/shims/io_error.rs
  src/shims/unix/linux/sync.rs
  src/shims/windows/sync.rs
Labels: S-waiting-on-author
